### ISSUE TITLE
Error with experimentcookie, index.html not working.

### ISSUE THREAD

**Issue by zoosky** [prismicio/javascript-jquery-starter#21]
in File /js/prismic-helpers.js prismic is not defined

           var experimentCookie = prismic.startExperiment ? prismic.utils.docCookies.getItem('io.prismic.experiment') : null;
            var experimentRef = experimentCookie ? api.experiments.refFromCookie(experimentCookie) : null;

**Comment by erwan** [comment]
this repo is no longer maintained
