### ISSUE TITLE
oauth support: problem with CORS headers and 401 response

### ISSUE THREAD

**Issue by ashelley** [prismicio/javascript-jquery-starter#7]
Hello,

I'm trying to connect to a private repository using oauth.  However, I don't believe the server is sending the proper headers back for the CORS request.  

Example, if i try to connect to my private repository I get this from chrome:

```
XMLHttpRequest cannot load https://mydomain.prismic.io/api. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. 
```

In firefox I get a similar problem:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mydomain.prismic.io/api. This can be fixed by moving the resource to the same domain or enabling CORS.
```

I've setup a proxy on my localhost to send back the proper headers to the browser and this gets me passed the problem however this code does not work even if the CORS problem didn't exist.  The response from the server I get is:

```
> xhr.status
401
> xhr.response
"{"error":"Invalid access token","oauth_initiate":"https://mydomain.prismic.io/auth","oauth_token":"https://mydomain.prismic.io/auth/token"}"
```

Because the non 200 response will cause a failure the signin.html code can never work because the error condition always prevents it from working.

From signin.html

```
Helpers.getApiHome(
    function(err, api) {
        if (err) { Configuration.onPrismicError(err); return; }
        document.location =
            api.data.oauthInitiate + 
            '?response_type=token' +
            '&client_id=' + encodeURIComponent(Configuration['clientId']) +
            '&redirect_uri=' + encodeURIComponent(document.location) +
            '&scope=' + encodeURIComponent('master+releases');
    }
);
```

Note: you can get an access token if you manually browse to the url that would normally be generated by signin.html if you manually enter the url into the browser: 

```
https://mydomain.prismic.io/auth?response_type=token&client_id=yourclientid&redirect_uri=http%3A%2F%2Flocalhost%3A3000&scope=master%2Breleases
```

Steps to reproduce:
1) make your repository private in prismic.io interface and add an application
2) change your prismic-configuration.js file to contain your clientId and clientSecret
3) try to access index.html or signin.html, you will get the cors error.

Note: if you use fiddler to decrypt the traffic you can see that the error response comes back but the browser still throws the cors error.

**Comment by gabzim** [comment]
I have this same issue, been using prismic for 2 days, things are getting frustrating

**Comment by erwan** [comment]
Hi,

@arg20 can you give some details about the problem you're having? This is an old ticket, the issue was fixed and the code base is very different from what it is now.

**Comment by desirelabs** [comment]
Same issue here with open api and only with Firefox and safari.
